; Change these variables to your desired setup

[Variables]
; The color of the icons (Set this to 255,255,255 if your icons have color)
IconColor = 255,255,255,255

; Save your icons inside the "@Resources\Icons" folder
; IconName  >> The name of the icon file saved in the icons folder (Ex: steam.png)
; IconPath  >> The path of the app that you want to launch (Ex: C:\Program Files (x86)\Steam\Steam.exe)

;========= Mid Icons =========

IconName1 = steam.png
IconPath1 = ["C:\Program files (x86)\Steam\Steam.exe"]

IconName4 = youtube.png
IconPath4 = ["https://www.youtube.com"]

